services:
  dev-java:
    container_name: 'dev-java'
    hostname: 'dev-java'
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    working_dir: '/workspace'
    volumes:
      - ../workspace:/workspace